site_name: "TinyML: Efficient Machine Learning for Embedded AI Systems"
docs_dir: .
site_dir: ../site
repo_url: https://github.com/wdmdev/tinyml-efficient-ml-for-embedded-ai

theme:
  language: en
  name: material
  favicon: figures/storm.png
  logo: figures/storm.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:anders-soerensen@hotmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/wdmdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/william-marstrand

nav:
  - Home: README.md